<?php

namespace App\Http\Controllers;

use PHPUnit\Framework\TestCase;

class UnitTestControllerTest extends TestCase
{
    protected UnitTestController $unitTestController;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->unitTestController = new UnitTestController();
    }

    public function testTest()
    {
        $test = $this->unitTestController->test(15);

        self::assertTrue($test);
    }
}
